version: '3'

services:

#  The Application
  app:
    container_name: clane_test_app
    build:
      context: ./
      dockerfile: development/app.dockerfile
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    env_file: '.env'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

# The Web Server
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./:/var/www
      - ./storage/logs/:/var/log/nginx
    ports:
      - 8990:80

# The Database
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=clane_test"
      - "MYSQL_USER=geebengs"
      - "MYSQL_PASSWORD=Sp@rkle123"
      - "MYSQL_ROOT_PASSWORD=geebengs123456"
    ports:
      - 8991:3306

# redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata: